# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_MAIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Database_control


global values, status

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 623)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Scereens = QtWidgets.QStackedWidget(self.centralwidget)
        self.Scereens.setGeometry(QtCore.QRect(0, 0, 811, 561))
        self.Scereens.setObjectName("Scereens")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.LogTitle = QtWidgets.QLabel(self.Login)
        self.LogTitle.setGeometry(QtCore.QRect(300, 60, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.LogTitle.setFont(font)
        self.LogTitle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.LogTitle.setAutoFillBackground(False)
        self.LogTitle.setObjectName("LogTitle")
        self.Username = QtWidgets.QLabel(self.Login)
        self.Username.setGeometry(QtCore.QRect(270, 160, 71, 16))
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLabel(self.Login)
        self.Password.setGeometry(QtCore.QRect(270, 220, 71, 16))
        self.Password.setObjectName("Password")
        self.LogError = QtWidgets.QLabel(self.Login)
        self.LogError.setGeometry(QtCore.QRect(240, 340, 351, 16))
        self.LogError.setStyleSheet("color: red;")
        self.LogError.setObjectName("LogError")
        self.UsernameE = QtWidgets.QLineEdit(self.Login)
        self.UsernameE.setGeometry(QtCore.QRect(260, 180, 261, 26))
        self.UsernameE.setObjectName("UsernameE")
        self.PasswordE = QtWidgets.QLineEdit(self.Login)
        self.PasswordE.setGeometry(QtCore.QRect(260, 240, 261, 26))
        self.PasswordE.setObjectName("PasswordE")
        self.LogBT = QtWidgets.QPushButton(self.Login)
        self.LogBT.setGeometry(QtCore.QRect(270, 290, 101, 26))
        self.LogBT.setObjectName("LogBT")
        self.LogBT.clicked.connect(self.login)
        self.Scereens.addWidget(self.Login)
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.ContactInfo = QtWidgets.QGroupBox(self.Info)
        self.ContactInfo.setGeometry(QtCore.QRect(220, 10, 341, 371))
        self.ContactInfo.setObjectName("ContactInfo")
        self.ParentName = QtWidgets.QLabel(self.ContactInfo)
        self.ParentName.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.ParentName.setObjectName("ParentName")
        self.ParentNameE = QtWidgets.QLabel(self.ContactInfo)
        self.ParentNameE.setGeometry(QtCore.QRect(100, 40, 7, 20))
        self.ParentNameE.setAutoFillBackground(True)
        self.ParentNameE.setText("")
        self.ParentNameE.setObjectName("ParentNameE")
        self.ChildName = QtWidgets.QLabel(self.ContactInfo)
        self.ChildName.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.ChildName.setObjectName("ChildName")
        self.ChildNameE = QtWidgets.QLabel(self.ContactInfo)
        self.ChildNameE.setGeometry(QtCore.QRect(80, 70, 0, 16))
        self.ChildNameE.setAutoFillBackground(True)
        self.ChildNameE.setText("")
        self.ChildNameE.setObjectName("ChildNameE")
        self.ChildAge = QtWidgets.QLabel(self.ContactInfo)
        self.ChildAge.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.ChildAge.setObjectName("ChildAge")
        self.ChildAgeE = QtWidgets.QLabel(self.ContactInfo)
        self.ChildAgeE.setGeometry(QtCore.QRect(80, 110, 7, 20))
        self.ChildAgeE.setAutoFillBackground(True)
        self.ChildAgeE.setText("")
        self.ChildAgeE.setObjectName("ChildAgeE")
        self.ChildGrade = QtWidgets.QLabel(self.ContactInfo)
        self.ChildGrade.setGeometry(QtCore.QRect(110, 110, 91, 16))
        self.ChildGrade.setObjectName("ChildGrade")
        self.ChildGradeE = QtWidgets.QLabel(self.ContactInfo)
        self.ChildGradeE.setGeometry(QtCore.QRect(190, 110, 7, 20))
        self.ChildGradeE.setAutoFillBackground(True)
        self.ChildGradeE.setText("")
        self.ChildGradeE.setObjectName("ChildGradeE")
        self.ParentEmail = QtWidgets.QLabel(self.ContactInfo)
        self.ParentEmail.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.ParentEmail.setObjectName("ParentEmail")
        self.ParentEmailE = QtWidgets.QLabel(self.ContactInfo)
        self.ParentEmailE.setGeometry(QtCore.QRect(100, 150, 7, 20))
        self.ParentEmailE.setAutoFillBackground(True)
        self.ParentEmailE.setText("")
        self.ParentEmailE.setObjectName("ParentEmailE")
        self.ParentNumber = QtWidgets.QLabel(self.ContactInfo)
        self.ParentNumber.setGeometry(QtCore.QRect(10, 190, 111, 16))
        self.ParentNumber.setObjectName("ParentNumber")
        self.ParentNumberE = QtWidgets.QLabel(self.ContactInfo)
        self.ParentNumberE.setGeometry(QtCore.QRect(110, 190, 7, 20))
        self.ParentNumberE.setAutoFillBackground(True)
        self.ParentNumberE.setText("")
        self.ParentNumberE.setObjectName("ParentNumberE")
        self.SecondaryParentName = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentName.setGeometry(QtCore.QRect(10, 230, 171, 16))
        self.SecondaryParentName.setObjectName("SecondaryParentName")
        self.SecondaryParentNameE = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentNameE.setGeometry(QtCore.QRect(170, 230, 7, 20))
        self.SecondaryParentNameE.setAutoFillBackground(True)
        self.SecondaryParentNameE.setText("")
        self.SecondaryParentNameE.setObjectName("SecondaryParentNameE")
        self.SecondaryParentEmail = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentEmail.setGeometry(QtCore.QRect(10, 270, 171, 16))
        self.SecondaryParentEmail.setObjectName("SecondaryParentEmail")
        self.SecondaryParentEmailE = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentEmailE.setGeometry(QtCore.QRect(170, 270, 7, 20))
        self.SecondaryParentEmailE.setAutoFillBackground(True)
        self.SecondaryParentEmailE.setText("")
        self.SecondaryParentEmailE.setObjectName("SecondaryParentEmailE")
        self.SecondaryParentNum = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentNum.setGeometry(QtCore.QRect(10, 310, 181, 16))
        self.SecondaryParentNum.setObjectName("SecondaryParentNum")
        self.SecondaryParentNumE = QtWidgets.QLabel(self.ContactInfo)
        self.SecondaryParentNumE.setGeometry(QtCore.QRect(190, 310, 7, 20))
        self.SecondaryParentNumE.setAutoFillBackground(True)
        self.SecondaryParentNumE.setText("")
        self.SecondaryParentNumE.setObjectName("SecondaryParentNumE")
        self.FilledFrom = QtWidgets.QLabel(self.ContactInfo)
        self.FilledFrom.setGeometry(QtCore.QRect(10, 340, 81, 16))
        self.FilledFrom.setObjectName("FilledFrom")
        self.FilledFromE = QtWidgets.QLabel(self.ContactInfo)
        self.FilledFromE.setGeometry(QtCore.QRect(90, 340, 6, 16))
        self.FilledFromE.setAutoFillBackground(True)
        self.FilledFromE.setText("")
        self.FilledFromE.setObjectName("FilledFromE")
        self.Back = QtWidgets.QPushButton(self.Info)
        self.Back.setGeometry(QtCore.QRect(90, 450, 81, 26))
        self.Back.setObjectName("Back")
        self.SaveBT2 = QtWidgets.QPushButton(self.Info)
        self.SaveBT2.setGeometry(QtCore.QRect(310, 450, 131, 26))
        self.SaveBT2.setObjectName("SaveBT2")
        self.SaveBT2.setEnabled(False)
        self.SaveBT1 = QtWidgets.QPushButton(self.Info)
        self.SaveBT1.setGeometry(QtCore.QRect(560, 450, 121, 26))
        self.SaveBT1.setObjectName("SaveBT1")
        self.SaveBT1.setEnabled(False)
        self.SaveConfirm = QtWidgets.QLabel(self.Info)
        self.SaveConfirm.setGeometry(QtCore.QRect(310, 390, 131, 20))
        self.SaveConfirm.setStyleSheet("color: green;")
        self.SaveConfirm.setObjectName("SaveConfirm")
        self.Scereens.addWidget(self.Info)
        self.Contacts = QtWidgets.QWidget()
        self.Contacts.setObjectName("Contacts")
        self.ConTitle = QtWidgets.QLabel(self.Contacts)
        self.ConTitle.setGeometry(QtCore.QRect(140, 40, 521, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.ConTitle.setFont(font)
        self.ConTitle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ConTitle.setAutoFillBackground(False)
        self.ConTitle.setObjectName("ConTitle")
        self.HelpNav = QtWidgets.QLabel(self.Contacts)
        self.HelpNav.setGeometry(QtCore.QRect(240, 150, 341, 16))
        self.HelpNav.setObjectName("HelpNav")
        self.NameList = QtWidgets.QListWidget(self.Contacts)
        self.NameList.setGeometry(QtCore.QRect(240, 300, 256, 192))
        self.NameList.setObjectName("NameList")
        self.NameList.itemClicked.connect(self.contactinfo)
        self.StatusList = QtWidgets.QListWidget(self.Contacts)
        self.StatusList.setGeometry(QtCore.QRect(490, 300, 91, 192))
        self.StatusList.setObjectName("StatusList")
        self.HelpS = QtWidgets.QLabel(self.Contacts)
        self.HelpS.setGeometry(QtCore.QRect(240, 220, 341, 20))
        self.HelpS.setWordWrap(False)
        self.HelpS.setObjectName("HelpS")
        self.SearchE = QtWidgets.QLineEdit(self.Contacts)
        self.SearchE.setGeometry(QtCore.QRect(240, 260, 251, 26))
        self.SearchE.setObjectName("SearchE")
        self.SearchBT = QtWidgets.QPushButton(self.Contacts)
        self.SearchBT.setGeometry(QtCore.QRect(500, 260, 81, 26))
        self.SearchBT.setObjectName("SearchBT")
        self.SearchBT.clicked.connect(self.search)
        self.Scereens.addWidget(self.Contacts)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Scereens.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):*
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CRM for NEXT Goa"))
        self.LogTitle.setText(_translate("MainWindow", "Login"))
        self.Username.setText(_translate("MainWindow", "Username:"))
        self.Password.setText(_translate("MainWindow", "Password:"))
        self.LogBT.setText(_translate("MainWindow", "Login"))
        self.ContactInfo.setTitle(_translate("MainWindow", "Contact info"))
        self.ParentName.setText(_translate("MainWindow", "Parent name:"))
        self.ChildName.setText(_translate("MainWindow", "Child name:"))
        self.ChildAge.setText(_translate("MainWindow", "Child age:"))
        self.ChildGrade.setText(_translate("MainWindow", "Child grade:"))
        self.ParentEmail.setText(_translate("MainWindow", "Parent email:"))
        self.ParentNumber.setText(_translate("MainWindow", "Parent number:"))
        self.SecondaryParentName.setText(_translate("MainWindow", "Secondary parent name:"))
        self.SecondaryParentEmail.setText(_translate("MainWindow", "Secondary parent email:"))
        self.SecondaryParentNum.setText(_translate("MainWindow", "Secondary parent number:"))
        self.FilledFrom.setText(_translate("MainWindow", "Filled from:"))
        self.Back.setText(_translate("MainWindow", "Back"))
        self.SaveBT2.setText(_translate("MainWindow", "Save to continued"))
        self.SaveBT1.setText(_translate("MainWindow", "Save to rejected"))
        self.ConTitle.setText(_translate("MainWindow", "You are now in: pending"))
        self.HelpNav.setText(_translate("MainWindow", "Use the menue to travel between scereens or use it to log out"))
        self.HelpS.setText(_translate("MainWindow", "You can search for pending contcts with name, phone number, or email"))
        self.SearchBT.setText(_translate("MainWindow", "Search"))
        self.update()


    def update(self):
        self.LogError.adjustSize()
        self.ParentNameE.adjustSize()
        self.ChildNameE.adjustSize()
        self.ChildAgeE.adjustSize()
        self.ChildGradeE.adjustSize()
        self.ParentEmailE.adjustSize()
        self.ParentNumberE.adjustSize()
        self.SecondaryParentNameE.adjustSize()
        self.SecondaryParentEmailE.adjustSize()
        self.SecondaryParentNumE.adjustSize()
        self.FilledFromE.adjustSize()
        self.ConTitle.adjustSize()
        self.HelpNav.adjustSize()
        self.HelpS.adjustSize()


    def login(self):
        if self.UsernameE.text() == "test" and self.PasswordE.text() == "1234":
            self.LogError.setText("")
            self.update()
            self.Scereens.setCurrentIndex(2)
            self.pending()
        else:
            self.LogError.setText("Error loging in, password or username are incorrect")
            self.update()


    def pending(self):
        global values, status
        self.SaveConfirm.setText("")
        self.ConTitle.setText("You are now in: pending")
        self.HelpS.setText("You can search for pending contacts with name, phone number, or email")
        self.menubar.clear()
        goto=self.menubar.addMenu("Go to")
        pending=goto.addAction("pending")
        pending.triggered.connect(self.pending)
        continued=goto.addAction("continued")
        continued.triggered.connect(self.continued)
        rejected=goto.addAction("rejected")
        rejected.triggered.connect(self.Rejected)
        Logout=self.menubar.addAction("Logout")
        Logout.triggered.connect(self.logout)
        self.update()
        self.NameList.clear()
        self.StatusList.clear()
        self.visible_rows = []
        values=Database_control.get_raw_data(Database_control.get_sheet_vals(Database_control.sheet_id))
        for i in range(len(values)):
            row_status = values[i][11] if len(values[i]) > 11 else ""
            if str(row_status).strip().lower()=="pending":
                self.NameList.addItem(values[i][1])
                self.StatusList.addItem("pending")
                self.visible_rows.append((i + 2, values[i]))
            elif row_status in (None, ""):
                Database_control.update_status(Database_control.sheet_id, i+2, 12, "pending")
                if len(values[i]) > 11:
                    values[i][11] = "pending"
                self.NameList.addItem(values[i][1])
                self.StatusList.addItem("pending")
                self.visible_rows.append((i + 2, values[i]))
        status="pending"

    def continued(self):
        global values, status
        self.SaveConfirm.setText("")
        self.ConTitle.setText("You are now in: continued")
        self.HelpS.setText("You can search for continued contacts with name, phone number, or email")
        self.menubar.clear()
        goto=self.menubar.addMenu("Go to")
        pending=goto.addAction("pending")
        pending.triggered.connect(self.pending)
        continued=goto.addAction("continued")
        continued.triggered.connect(self.continued)
        rejected=goto.addAction("rejected")
        rejected.triggered.connect(self.Rejected)
        Logout=self.menubar.addAction("Logout")
        Logout.triggered.connect(self.logout)
        self.update()
        self.NameList.clear()
        self.StatusList.clear()
        self.visible_rows = []
        values=Database_control.get_raw_data(Database_control.get_sheet_vals(Database_control.sheet_id))
        for i in range(len(values)):
            if values[i][11]=="continued":
                self.NameList.addItem(values[i][1])
                self.StatusList.addItem(values[i][11])
            self.visible_rows.append((i + 2, values[i]))
        status="continued"

    def Rejected(self):
        global values, status
        self.SaveConfirm.setText("")
        self.ConTitle.setText("You are now in: rejected")
        self.HelpS.setText("You can search for rejected contacts with name, phone number, or email")
        self.menubar.clear()
        goto=self.menubar.addMenu("Go to")
        pending=goto.addAction("pending")
        pending.triggered.connect(self.pending)
        continued=goto.addAction("continued")
        continued.triggered.connect(self.continued)
        rejected=goto.addAction("rejected")
        rejected.triggered.connect(self.Rejected)
        Logout=self.menubar.addAction("Logout")
        Logout.triggered.connect(self.logout)
        self.update()
        self.NameList.clear()
        self.StatusList.clear()
        self.visible_rows = []
        values=Database_control.get_raw_data(Database_control.get_sheet_vals(Database_control.sheet_id))
        for i in range(len(values)):
            if values[i][11]=="rejected":
                self.NameList.addItem(values[i][1])
                self.StatusList.addItem(values[i][11])
            self.visible_rows.append((i + 2, values[i]))
        status="rejected"

    def search(self):
        global values, status
        self.NameList.clear()
        self.StatusList.clear()
        self.visible_rows = []
        search_text = self.SearchE.text()
        for i in range(len(values)):
            if search_text in str(values[i][1]) or search_text in str(values[i][2]) or search_text in str(values[i][5]) or search_text in str(values[i][6]) or search_text in str(values[i][7]) or search_text in str(values[i][8]) or search_text in str(values[i][9]):
                if values[i][11]==status:
                    self.NameList.addItem(values[i][1])
                    self.StatusList.addItem(values[i][11])
                    self.visible_rows.append((i + 2, values[i]))

    def contactinfo(self):
        global values, status
        self.menubar.clear()
        i=self.NameList.currentRow()
        if i < 0 or i >= len(self.visible_rows):
            return
        self.Scereens.setCurrentIndex(1)
        self.selected_sheet_row, selected_row = self.visible_rows[i]
        self.ParentNameE.setText(str(selected_row[1]))
        self.ChildNameE.setText(str(selected_row[2]))
        self.ChildAgeE.setText(str(selected_row[3]))
        self.ChildGradeE.setText(str(selected_row[4]))
        self.ParentEmailE.setText(str(selected_row[5]))
        self.ParentNumberE.setText(str(selected_row[6]))
        self.SecondaryParentNameE.setText(str(selected_row[7]))
        self.SecondaryParentEmailE.setText(str(selected_row[8]))
        self.SecondaryParentNumE.setText(str(selected_row[9]))
        self.FilledFromE.setText(str(selected_row[10]))
        self.update()
        try:
            self.SaveBT1.clicked.disconnect()
        except TypeError:
            pass
        try:
            self.SaveBT2.clicked.disconnect()
        except TypeError:
            pass
        self.SaveBT1.setText("Save to rejected")
        self.SaveBT2.setText("Save to continued")
        if status == "pending":
            self.SaveBT1.setEnabled(True)
            self.SaveBT1.clicked.connect(self.save_rejected)
            self.SaveBT2.setEnabled(True)
            self.SaveBT2.clicked.connect(self.save_continued)
        elif status == "continued":
            self.SaveBT1.setEnabled(True)
            self.SaveBT1.clicked.connect(self.save_rejected)
            self.SaveBT2.setEnabled(False)
        elif status == "rejected":
            self.SaveBT2.setEnabled(True)
            self.SaveBT2.clicked.connect(self.save_continued)
            self.SaveBT1.setEnabled(False)

    def back(self):
        self.Scereens.setCurrentIndex(2)


    def finish_save_and_return(self, refresh_view):
        self.SaveConfirm.setText("")
        refresh_view()
        self.Scereens.setCurrentIndex(2)


    def save_continued(self):
        if self.selected_sheet_row is not None and status!="continued":
            Database_control.update_status(Database_control.sheet_id, self.selected_sheet_row, 12, "continued")
            self.SaveConfirm.setText("Saved to continued")
            self.update()
            if status=="pending":
                QtCore.QTimer.singleShot(1000, lambda: self.finish_save_and_return(self.pending))
            elif status=="rejected":
                QtCore.QTimer.singleShot(1000, lambda: self.finish_save_and_return(self.Rejected))

    def save_rejected(self):
        if self.selected_sheet_row is not None and status!="rejected":
            Database_control.update_status(Database_control.sheet_id, self.selected_sheet_row, 12, "rejected")
            self.SaveConfirm.setText("Saved to rejected")
            self.update()
            if status=="pending":
                QtCore.QTimer.singleShot(1000, lambda: self.finish_save_and_return(self.pending))
            elif status=="continued":
                QtCore.QTimer.singleShot(1000, lambda: self.finish_save_and_return(self.continued))
    def logout(self):
        self.Scereens.setCurrentIndex(0)
        self.menubar.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
